/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_v1_common_pb = require('./common/v1/common_pb.js');
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.arangodb.cloud.platform.v1.Provider', null, global);
goog.exportSymbol('proto.arangodb.cloud.platform.v1.ProviderList', null, global);
goog.exportSymbol('proto.arangodb.cloud.platform.v1.Region', null, global);
goog.exportSymbol('proto.arangodb.cloud.platform.v1.RegionList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.platform.v1.Provider = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.platform.v1.Provider, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.platform.v1.Provider.displayName = 'proto.arangodb.cloud.platform.v1.Provider';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.platform.v1.Provider.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.platform.v1.Provider.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.platform.v1.Provider} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.Provider.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.platform.v1.Provider}
 */
proto.arangodb.cloud.platform.v1.Provider.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.platform.v1.Provider;
  return proto.arangodb.cloud.platform.v1.Provider.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.platform.v1.Provider} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.platform.v1.Provider}
 */
proto.arangodb.cloud.platform.v1.Provider.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.platform.v1.Provider.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.platform.v1.Provider.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.platform.v1.Provider} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.Provider.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.platform.v1.Provider.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.platform.v1.Provider.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.arangodb.cloud.platform.v1.Provider.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.platform.v1.Provider.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.platform.v1.ProviderList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.platform.v1.ProviderList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.platform.v1.ProviderList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.platform.v1.ProviderList.displayName = 'proto.arangodb.cloud.platform.v1.ProviderList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.platform.v1.ProviderList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.platform.v1.ProviderList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.platform.v1.ProviderList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.platform.v1.ProviderList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.ProviderList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.platform.v1.Provider.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.platform.v1.ProviderList}
 */
proto.arangodb.cloud.platform.v1.ProviderList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.platform.v1.ProviderList;
  return proto.arangodb.cloud.platform.v1.ProviderList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.platform.v1.ProviderList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.platform.v1.ProviderList}
 */
proto.arangodb.cloud.platform.v1.ProviderList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.platform.v1.Provider;
      reader.readMessage(value,proto.arangodb.cloud.platform.v1.Provider.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.platform.v1.ProviderList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.platform.v1.ProviderList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.platform.v1.ProviderList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.ProviderList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.platform.v1.Provider.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Provider items = 1;
 * @return {!Array<!proto.arangodb.cloud.platform.v1.Provider>}
 */
proto.arangodb.cloud.platform.v1.ProviderList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.platform.v1.Provider>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.platform.v1.Provider, 1));
};


/** @param {!Array<!proto.arangodb.cloud.platform.v1.Provider>} value */
proto.arangodb.cloud.platform.v1.ProviderList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.platform.v1.Provider=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.platform.v1.Provider}
 */
proto.arangodb.cloud.platform.v1.ProviderList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.platform.v1.Provider, opt_index);
};


proto.arangodb.cloud.platform.v1.ProviderList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.platform.v1.Region = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.platform.v1.Region, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.platform.v1.Region.displayName = 'proto.arangodb.cloud.platform.v1.Region';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.platform.v1.Region.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.platform.v1.Region} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.Region.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    providerId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    location: jspb.Message.getFieldWithDefault(msg, 3, ""),
    available: jspb.Message.getFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.platform.v1.Region}
 */
proto.arangodb.cloud.platform.v1.Region.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.platform.v1.Region;
  return proto.arangodb.cloud.platform.v1.Region.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.platform.v1.Region} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.platform.v1.Region}
 */
proto.arangodb.cloud.platform.v1.Region.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLocation(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAvailable(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.platform.v1.Region.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.platform.v1.Region} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.Region.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProviderId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLocation();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAvailable();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.platform.v1.Region.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string provider_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.getProviderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.platform.v1.Region.prototype.setProviderId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string location = 3;
 * @return {string}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.getLocation = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.platform.v1.Region.prototype.setLocation = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool available = 4;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.arangodb.cloud.platform.v1.Region.prototype.getAvailable = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 4, false));
};


/** @param {boolean} value */
proto.arangodb.cloud.platform.v1.Region.prototype.setAvailable = function(value) {
  jspb.Message.setProto3BooleanField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.platform.v1.RegionList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.platform.v1.RegionList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.platform.v1.RegionList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.platform.v1.RegionList.displayName = 'proto.arangodb.cloud.platform.v1.RegionList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.platform.v1.RegionList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.platform.v1.RegionList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.platform.v1.RegionList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.platform.v1.RegionList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.RegionList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.platform.v1.Region.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.platform.v1.RegionList}
 */
proto.arangodb.cloud.platform.v1.RegionList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.platform.v1.RegionList;
  return proto.arangodb.cloud.platform.v1.RegionList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.platform.v1.RegionList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.platform.v1.RegionList}
 */
proto.arangodb.cloud.platform.v1.RegionList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.platform.v1.Region;
      reader.readMessage(value,proto.arangodb.cloud.platform.v1.Region.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.platform.v1.RegionList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.platform.v1.RegionList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.platform.v1.RegionList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.platform.v1.RegionList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.platform.v1.Region.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Region items = 1;
 * @return {!Array<!proto.arangodb.cloud.platform.v1.Region>}
 */
proto.arangodb.cloud.platform.v1.RegionList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.platform.v1.Region>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.platform.v1.Region, 1));
};


/** @param {!Array<!proto.arangodb.cloud.platform.v1.Region>} value */
proto.arangodb.cloud.platform.v1.RegionList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.platform.v1.Region=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.platform.v1.Region}
 */
proto.arangodb.cloud.platform.v1.RegionList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.platform.v1.Region, opt_index);
};


proto.arangodb.cloud.platform.v1.RegionList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};


goog.object.extend(exports, proto.arangodb.cloud.platform.v1);
