version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.5
    working_directory: /go/src/github.com/arangodb-managed/apis
    steps:
      - checkout
      - setup_remote_docker
      - run: make build-image all
      - run: make test

workflows:
  version: 2
  build:
    jobs:
      - build
