/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_v1_common_pb = require('./common/v1/common_pb.js');
var github_com_golang_protobuf_ptypes_timestamp_timestamp_pb = require('./github.com/golang/protobuf/ptypes/timestamp/timestamp_pb.js');
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.arangodb.cloud.iam.v1.Group', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.GroupList', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.GroupMemberList', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.GroupMembersRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.HasPermissionsRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.PermissionList', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.Policy', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.Role', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.RoleBinding', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.RoleBindingsRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.RoleList', null, global);
goog.exportSymbol('proto.arangodb.cloud.iam.v1.User', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.User.displayName = 'proto.arangodb.cloud.iam.v1.User';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.User.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    givenName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    familyName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.User}
 */
proto.arangodb.cloud.iam.v1.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.User;
  return proto.arangodb.cloud.iam.v1.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.User}
 */
proto.arangodb.cloud.iam.v1.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setGivenName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamilyName(value);
      break;
    case 6:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGivenName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFamilyName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.User.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.User.prototype.setEmail = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.User.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string given_name = 4;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getGivenName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.User.prototype.setGivenName = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string family_name = 5;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getFamilyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.User.prototype.setFamilyName = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.iam.v1.User.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.iam.v1.User.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.arangodb.cloud.iam.v1.User.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.iam.v1.User.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.Group = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.Group, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.Group.displayName = 'proto.arangodb.cloud.iam.v1.Group';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.Group.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.Group} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Group.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organizationId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.Group}
 */
proto.arangodb.cloud.iam.v1.Group.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.Group;
  return proto.arangodb.cloud.iam.v1.Group.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.Group} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.Group}
 */
proto.arangodb.cloud.iam.v1.Group.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.Group.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.Group} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Group.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrganizationId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Group.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string organization_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.getOrganizationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Group.prototype.setOrganizationId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Group.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Group.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 5));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.iam.v1.Group.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.arangodb.cloud.iam.v1.Group.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.iam.v1.Group.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.GroupList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.GroupList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.GroupList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.GroupList.displayName = 'proto.arangodb.cloud.iam.v1.GroupList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.GroupList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.GroupList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.GroupList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.GroupList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.iam.v1.Group.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.GroupList}
 */
proto.arangodb.cloud.iam.v1.GroupList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.GroupList;
  return proto.arangodb.cloud.iam.v1.GroupList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.GroupList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.GroupList}
 */
proto.arangodb.cloud.iam.v1.GroupList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.iam.v1.Group;
      reader.readMessage(value,proto.arangodb.cloud.iam.v1.Group.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.GroupList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.GroupList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.GroupList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.iam.v1.Group.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Group items = 1;
 * @return {!Array<!proto.arangodb.cloud.iam.v1.Group>}
 */
proto.arangodb.cloud.iam.v1.GroupList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.iam.v1.Group>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.iam.v1.Group, 1));
};


/** @param {!Array<!proto.arangodb.cloud.iam.v1.Group>} value */
proto.arangodb.cloud.iam.v1.GroupList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.iam.v1.Group=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.iam.v1.Group}
 */
proto.arangodb.cloud.iam.v1.GroupList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.iam.v1.Group, opt_index);
};


proto.arangodb.cloud.iam.v1.GroupList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.displayName = 'proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    groupId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest;
  return proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroupId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGroupId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string group_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.getGroupId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.IsMemberOfGroupRequest.prototype.setGroupId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.GroupMemberList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.GroupMemberList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.GroupMemberList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.GroupMemberList.displayName = 'proto.arangodb.cloud.iam.v1.GroupMemberList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.GroupMemberList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.GroupMemberList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.getRepeatedField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.GroupMemberList}
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.GroupMemberList;
  return proto.arangodb.cloud.iam.v1.GroupMemberList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.GroupMemberList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.GroupMemberList}
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.GroupMemberList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.GroupMemberList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string items = 1;
 * @return {!Array<string>}
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.getItemsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.setItemsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.addItems = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.arangodb.cloud.iam.v1.GroupMemberList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.GroupMembersRequest.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.GroupMembersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.GroupMembersRequest.displayName = 'proto.arangodb.cloud.iam.v1.GroupMembersRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.GroupMembersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.GroupMembersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    groupId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userIdsList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.GroupMembersRequest}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.GroupMembersRequest;
  return proto.arangodb.cloud.iam.v1.GroupMembersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.GroupMembersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.GroupMembersRequest}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroupId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addUserIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.GroupMembersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.GroupMembersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getGroupId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string group_id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.getGroupId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.setGroupId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string user_ids = 2;
 * @return {!Array<string>}
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.getUserIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.setUserIdsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.addUserIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.arangodb.cloud.iam.v1.GroupMembersRequest.prototype.clearUserIdsList = function() {
  this.setUserIdsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.PermissionList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.PermissionList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.PermissionList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.PermissionList.displayName = 'proto.arangodb.cloud.iam.v1.PermissionList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.PermissionList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.PermissionList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.PermissionList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.PermissionList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.PermissionList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.getRepeatedField(msg, 1)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.PermissionList}
 */
proto.arangodb.cloud.iam.v1.PermissionList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.PermissionList;
  return proto.arangodb.cloud.iam.v1.PermissionList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.PermissionList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.PermissionList}
 */
proto.arangodb.cloud.iam.v1.PermissionList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.PermissionList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.PermissionList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.PermissionList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.PermissionList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string items = 1;
 * @return {!Array<string>}
 */
proto.arangodb.cloud.iam.v1.PermissionList.prototype.getItemsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.arangodb.cloud.iam.v1.PermissionList.prototype.setItemsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.arangodb.cloud.iam.v1.PermissionList.prototype.addItems = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.arangodb.cloud.iam.v1.PermissionList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.HasPermissionsRequest.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.HasPermissionsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.HasPermissionsRequest.displayName = 'proto.arangodb.cloud.iam.v1.HasPermissionsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.HasPermissionsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.HasPermissionsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    permissionsList: jspb.Message.getRepeatedField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.HasPermissionsRequest}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.HasPermissionsRequest;
  return proto.arangodb.cloud.iam.v1.HasPermissionsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.HasPermissionsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.HasPermissionsRequest}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addPermissions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.HasPermissionsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.HasPermissionsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string permissions = 2;
 * @return {!Array<string>}
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.getPermissionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/** @param {!Array<string>} value */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.setPermissionsList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.addPermissions = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.arangodb.cloud.iam.v1.HasPermissionsRequest.prototype.clearPermissionsList = function() {
  this.setPermissionsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.Role = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.Role.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.Role, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.Role.displayName = 'proto.arangodb.cloud.iam.v1.Role';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.Role.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.Role.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.Role} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Role.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organizationId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    permissionsList: jspb.Message.getRepeatedField(msg, 5),
    isPredefined: jspb.Message.getFieldWithDefault(msg, 6, false),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.Role}
 */
proto.arangodb.cloud.iam.v1.Role.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.Role;
  return proto.arangodb.cloud.iam.v1.Role.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.Role} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.Role}
 */
proto.arangodb.cloud.iam.v1.Role.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addPermissions(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPredefined(value);
      break;
    case 7:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.Role.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.Role} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Role.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrganizationId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPermissionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getIsPredefined();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string organization_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getOrganizationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setOrganizationId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string permissions = 5;
 * @return {!Array<string>}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getPermissionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setPermissionsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.arangodb.cloud.iam.v1.Role.prototype.addPermissions = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


proto.arangodb.cloud.iam.v1.Role.prototype.clearPermissionsList = function() {
  this.setPermissionsList([]);
};


/**
 * optional bool is_predefined = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getIsPredefined = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setIsPredefined = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.iam.v1.Role.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.arangodb.cloud.iam.v1.Role.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.iam.v1.Role.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.RoleList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.RoleList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.RoleList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.RoleList.displayName = 'proto.arangodb.cloud.iam.v1.RoleList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.RoleList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.RoleList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.RoleList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.RoleList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.iam.v1.Role.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.RoleList}
 */
proto.arangodb.cloud.iam.v1.RoleList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.RoleList;
  return proto.arangodb.cloud.iam.v1.RoleList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.RoleList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.RoleList}
 */
proto.arangodb.cloud.iam.v1.RoleList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.iam.v1.Role;
      reader.readMessage(value,proto.arangodb.cloud.iam.v1.Role.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.RoleList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.RoleList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.RoleList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.iam.v1.Role.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Role items = 1;
 * @return {!Array<!proto.arangodb.cloud.iam.v1.Role>}
 */
proto.arangodb.cloud.iam.v1.RoleList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.iam.v1.Role>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.iam.v1.Role, 1));
};


/** @param {!Array<!proto.arangodb.cloud.iam.v1.Role>} value */
proto.arangodb.cloud.iam.v1.RoleList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.iam.v1.Role=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.iam.v1.Role}
 */
proto.arangodb.cloud.iam.v1.RoleList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.iam.v1.Role, opt_index);
};


proto.arangodb.cloud.iam.v1.RoleList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.RoleBinding = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.RoleBinding, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.RoleBinding.displayName = 'proto.arangodb.cloud.iam.v1.RoleBinding';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.RoleBinding.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.RoleBinding} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleBinding.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    memberId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    roleId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.RoleBinding}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.RoleBinding;
  return proto.arangodb.cloud.iam.v1.RoleBinding.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.RoleBinding} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.RoleBinding}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoleId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.RoleBinding.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.RoleBinding} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleBinding.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMemberId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRoleId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string member_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.getMemberId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.setMemberId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string role_id = 3;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.getRoleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.RoleBinding.prototype.setRoleId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.Policy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.Policy.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.Policy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.Policy.displayName = 'proto.arangodb.cloud.iam.v1.Policy';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.Policy.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.Policy.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.Policy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.Policy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Policy.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceUrl: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bindingsList: jspb.Message.toObjectList(msg.getBindingsList(),
    proto.arangodb.cloud.iam.v1.RoleBinding.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.Policy}
 */
proto.arangodb.cloud.iam.v1.Policy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.Policy;
  return proto.arangodb.cloud.iam.v1.Policy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.Policy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.Policy}
 */
proto.arangodb.cloud.iam.v1.Policy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceUrl(value);
      break;
    case 2:
      var value = new proto.arangodb.cloud.iam.v1.RoleBinding;
      reader.readMessage(value,proto.arangodb.cloud.iam.v1.RoleBinding.deserializeBinaryFromReader);
      msg.addBindings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.Policy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.Policy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.Policy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.Policy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBindingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.arangodb.cloud.iam.v1.RoleBinding.serializeBinaryToWriter
    );
  }
};


/**
 * optional string resource_url = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.Policy.prototype.getResourceUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.Policy.prototype.setResourceUrl = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated RoleBinding bindings = 2;
 * @return {!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>}
 */
proto.arangodb.cloud.iam.v1.Policy.prototype.getBindingsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.iam.v1.RoleBinding, 2));
};


/** @param {!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>} value */
proto.arangodb.cloud.iam.v1.Policy.prototype.setBindingsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.arangodb.cloud.iam.v1.RoleBinding=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.iam.v1.RoleBinding}
 */
proto.arangodb.cloud.iam.v1.Policy.prototype.addBindings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.arangodb.cloud.iam.v1.RoleBinding, opt_index);
};


proto.arangodb.cloud.iam.v1.Policy.prototype.clearBindingsList = function() {
  this.setBindingsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.iam.v1.RoleBindingsRequest.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.iam.v1.RoleBindingsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.iam.v1.RoleBindingsRequest.displayName = 'proto.arangodb.cloud.iam.v1.RoleBindingsRequest';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.iam.v1.RoleBindingsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.iam.v1.RoleBindingsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceUrl: jspb.Message.getFieldWithDefault(msg, 1, ""),
    bindingsList: jspb.Message.toObjectList(msg.getBindingsList(),
    proto.arangodb.cloud.iam.v1.RoleBinding.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.iam.v1.RoleBindingsRequest}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.iam.v1.RoleBindingsRequest;
  return proto.arangodb.cloud.iam.v1.RoleBindingsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.iam.v1.RoleBindingsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.iam.v1.RoleBindingsRequest}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceUrl(value);
      break;
    case 2:
      var value = new proto.arangodb.cloud.iam.v1.RoleBinding;
      reader.readMessage(value,proto.arangodb.cloud.iam.v1.RoleBinding.deserializeBinaryFromReader);
      msg.addBindings(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.iam.v1.RoleBindingsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.iam.v1.RoleBindingsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getBindingsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.arangodb.cloud.iam.v1.RoleBinding.serializeBinaryToWriter
    );
  }
};


/**
 * optional string resource_url = 1;
 * @return {string}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.getResourceUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.setResourceUrl = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated RoleBinding bindings = 2;
 * @return {!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.getBindingsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.iam.v1.RoleBinding, 2));
};


/** @param {!Array<!proto.arangodb.cloud.iam.v1.RoleBinding>} value */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.setBindingsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.arangodb.cloud.iam.v1.RoleBinding=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.iam.v1.RoleBinding}
 */
proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.addBindings = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.arangodb.cloud.iam.v1.RoleBinding, opt_index);
};


proto.arangodb.cloud.iam.v1.RoleBindingsRequest.prototype.clearBindingsList = function() {
  this.setBindingsList([]);
};


goog.object.extend(exports, proto.arangodb.cloud.iam.v1);
