/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_v1_common_pb = require('./common/v1/common_pb.js');
var github_com_golang_protobuf_ptypes_duration_duration_pb = require('./github.com/golang/protobuf/ptypes/duration/duration_pb.js');
var github_com_golang_protobuf_ptypes_timestamp_timestamp_pb = require('./github.com/golang/protobuf/ptypes/timestamp/timestamp_pb.js');
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.arangodb.cloud.crypto.v1.CACertificate', null, global);
goog.exportSymbol('proto.arangodb.cloud.crypto.v1.CACertificateList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.crypto.v1.CACertificate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.crypto.v1.CACertificate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.crypto.v1.CACertificate.displayName = 'proto.arangodb.cloud.crypto.v1.CACertificate';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.crypto.v1.CACertificate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.crypto.v1.CACertificate.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    projectId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    lifetime: (f = msg.getLifetime()) && github_com_golang_protobuf_ptypes_duration_duration_pb.Duration.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    expiresAt: (f = msg.getExpiresAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    certificatePem: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.crypto.v1.CACertificate}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.crypto.v1.CACertificate;
  return proto.arangodb.cloud.crypto.v1.CACertificate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.crypto.v1.CACertificate}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectId(value);
      break;
    case 6:
      var value = new github_com_golang_protobuf_ptypes_duration_duration_pb.Duration;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_duration_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setLifetime(value);
      break;
    case 7:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 8:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    case 9:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setExpiresAt(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCertificatePem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.crypto.v1.CACertificate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.crypto.v1.CACertificate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getProjectId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLifetime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      github_com_golang_protobuf_ptypes_duration_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getExpiresAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCertificatePem();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string project_id = 5;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getProjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setProjectId = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional google.protobuf.Duration lifetime = 6;
 * @return {?proto.google.protobuf.Duration}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getLifetime = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_duration_duration_pb.Duration, 6));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setLifetime = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.arangodb.cloud.crypto.v1.CACertificate.prototype.clearLifetime = function() {
  this.setLifetime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.hasLifetime = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.arangodb.cloud.crypto.v1.CACertificate.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setDeletedAt = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.arangodb.cloud.crypto.v1.CACertificate.prototype.clearDeletedAt = function() {
  this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp expires_at = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getExpiresAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setExpiresAt = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.arangodb.cloud.crypto.v1.CACertificate.prototype.clearExpiresAt = function() {
  this.setExpiresAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.hasExpiresAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string certificate_pem = 10;
 * @return {string}
 */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.getCertificatePem = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.arangodb.cloud.crypto.v1.CACertificate.prototype.setCertificatePem = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.crypto.v1.CACertificateList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.crypto.v1.CACertificateList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.crypto.v1.CACertificateList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.crypto.v1.CACertificateList.displayName = 'proto.arangodb.cloud.crypto.v1.CACertificateList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.crypto.v1.CACertificateList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificateList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.crypto.v1.CACertificate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.crypto.v1.CACertificateList}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.crypto.v1.CACertificateList;
  return proto.arangodb.cloud.crypto.v1.CACertificateList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificateList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.crypto.v1.CACertificateList}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.crypto.v1.CACertificate;
      reader.readMessage(value,proto.arangodb.cloud.crypto.v1.CACertificate.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.crypto.v1.CACertificateList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificateList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.crypto.v1.CACertificate.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CACertificate items = 1;
 * @return {!Array<!proto.arangodb.cloud.crypto.v1.CACertificate>}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.crypto.v1.CACertificate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.crypto.v1.CACertificate, 1));
};


/** @param {!Array<!proto.arangodb.cloud.crypto.v1.CACertificate>} value */
proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.crypto.v1.CACertificate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.crypto.v1.CACertificate}
 */
proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.crypto.v1.CACertificate, opt_index);
};


proto.arangodb.cloud.crypto.v1.CACertificateList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};


goog.object.extend(exports, proto.arangodb.cloud.crypto.v1);
