/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_v1_common_pb = require('./common/v1/common_pb.js');
var github_com_golang_protobuf_ptypes_timestamp_timestamp_pb = require('./github.com/golang/protobuf/ptypes/timestamp/timestamp_pb.js');
var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.Member', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.MemberList', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.Organization', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.OrganizationList', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.Project', null, global);
goog.exportSymbol('proto.arangodb.cloud.resourcemanager.v1.ProjectList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.Organization = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.Organization, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.Organization.displayName = 'proto.arangodb.cloud.resourcemanager.v1.Organization';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.Organization.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Organization} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    isDeleted: jspb.Message.getFieldWithDefault(msg, 5, false),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Organization}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.Organization;
  return proto.arangodb.cloud.resourcemanager.v1.Organization.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Organization} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Organization}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDeleted(value);
      break;
    case 6:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 7:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.Organization.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Organization} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIsDeleted();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional bool is_deleted = 5;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getIsDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 5, false));
};


/** @param {boolean} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setIsDeleted = function(value) {
  jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 6));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.setDeletedAt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.clearDeletedAt = function() {
  this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Organization.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.resourcemanager.v1.OrganizationList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.OrganizationList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.OrganizationList.displayName = 'proto.arangodb.cloud.resourcemanager.v1.OrganizationList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.OrganizationList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.resourcemanager.v1.Organization.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.OrganizationList}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.OrganizationList;
  return proto.arangodb.cloud.resourcemanager.v1.OrganizationList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.OrganizationList}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.resourcemanager.v1.Organization;
      reader.readMessage(value,proto.arangodb.cloud.resourcemanager.v1.Organization.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.OrganizationList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.resourcemanager.v1.Organization.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Organization items = 1;
 * @return {!Array<!proto.arangodb.cloud.resourcemanager.v1.Organization>}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.resourcemanager.v1.Organization>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.resourcemanager.v1.Organization, 1));
};


/** @param {!Array<!proto.arangodb.cloud.resourcemanager.v1.Organization>} value */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Organization=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Organization}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.resourcemanager.v1.Organization, opt_index);
};


proto.arangodb.cloud.resourcemanager.v1.OrganizationList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.Member = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.Member, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.Member.displayName = 'proto.arangodb.cloud.resourcemanager.v1.Member';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.Member.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Member} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Member.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    owner: jspb.Message.getFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Member}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.Member;
  return proto.arangodb.cloud.resourcemanager.v1.Member.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Member} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Member}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOwner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.Member.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Member} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Member.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOwner();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool owner = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.getOwner = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.arangodb.cloud.resourcemanager.v1.Member.prototype.setOwner = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.resourcemanager.v1.MemberList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.MemberList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.MemberList.displayName = 'proto.arangodb.cloud.resourcemanager.v1.MemberList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.MemberList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.MemberList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.resourcemanager.v1.Member.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.MemberList}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.MemberList;
  return proto.arangodb.cloud.resourcemanager.v1.MemberList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.MemberList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.MemberList}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.resourcemanager.v1.Member;
      reader.readMessage(value,proto.arangodb.cloud.resourcemanager.v1.Member.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.MemberList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.MemberList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.resourcemanager.v1.Member.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Member items = 1;
 * @return {!Array<!proto.arangodb.cloud.resourcemanager.v1.Member>}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.resourcemanager.v1.Member>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.resourcemanager.v1.Member, 1));
};


/** @param {!Array<!proto.arangodb.cloud.resourcemanager.v1.Member>} value */
proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Member=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Member}
 */
proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.resourcemanager.v1.Member, opt_index);
};


proto.arangodb.cloud.resourcemanager.v1.MemberList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.displayName = 'proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    organizationId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest;
  return proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrganizationId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.setUserId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string organization_id = 2;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.getOrganizationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.IsMemberOfOrganizationRequest.prototype.setOrganizationId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.displayName = 'proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    organizationId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    members: (f = msg.getMembers()) && proto.arangodb.cloud.resourcemanager.v1.MemberList.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest;
  return proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationId(value);
      break;
    case 2:
      var value = new proto.arangodb.cloud.resourcemanager.v1.MemberList;
      reader.readMessage(value,proto.arangodb.cloud.resourcemanager.v1.MemberList.deserializeBinaryFromReader);
      msg.setMembers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOrganizationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMembers();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.arangodb.cloud.resourcemanager.v1.MemberList.serializeBinaryToWriter
    );
  }
};


/**
 * optional string organization_id = 1;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.getOrganizationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.setOrganizationId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional MemberList members = 2;
 * @return {?proto.arangodb.cloud.resourcemanager.v1.MemberList}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.getMembers = function() {
  return /** @type{?proto.arangodb.cloud.resourcemanager.v1.MemberList} */ (
    jspb.Message.getWrapperField(this, proto.arangodb.cloud.resourcemanager.v1.MemberList, 2));
};


/** @param {?proto.arangodb.cloud.resourcemanager.v1.MemberList|undefined} value */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.setMembers = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.clearMembers = function() {
  this.setMembers(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.OrganizationMembersRequest.prototype.hasMembers = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.Project = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.Project, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.Project.displayName = 'proto.arangodb.cloud.resourcemanager.v1.Project';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.Project.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Project} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Project.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    url: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    organizationId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    isDeleted: jspb.Message.getFieldWithDefault(msg, 6, false),
    createdAt: (f = msg.getCreatedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedAt: (f = msg.getDeletedAt()) && github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Project}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.Project;
  return proto.arangodb.cloud.resourcemanager.v1.Project.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Project} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Project}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganizationId(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDeleted(value);
      break;
    case 7:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 8:
      var value = new github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp;
      reader.readMessage(value,github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.Project.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Project} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.Project.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getOrganizationId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIsDeleted();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setUrl = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string organization_id = 5;
 * @return {string}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getOrganizationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setOrganizationId = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bool is_deleted = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getIsDeleted = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 6, false));
};


/** @param {boolean} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setIsDeleted = function(value) {
  jspb.Message.setProto3BooleanField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 7));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setCreatedAt = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.arangodb.cloud.resourcemanager.v1.Project.prototype.clearCreatedAt = function() {
  this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_at = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.getDeletedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, github_com_golang_protobuf_ptypes_timestamp_timestamp_pb.Timestamp, 8));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.setDeletedAt = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.arangodb.cloud.resourcemanager.v1.Project.prototype.clearDeletedAt = function() {
  this.setDeletedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.arangodb.cloud.resourcemanager.v1.Project.prototype.hasDeletedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.arangodb.cloud.resourcemanager.v1.ProjectList.repeatedFields_, null);
};
goog.inherits(proto.arangodb.cloud.resourcemanager.v1.ProjectList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.arangodb.cloud.resourcemanager.v1.ProjectList.displayName = 'proto.arangodb.cloud.resourcemanager.v1.ProjectList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.toObject = function(opt_includeInstance) {
  return proto.arangodb.cloud.resourcemanager.v1.ProjectList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.arangodb.cloud.resourcemanager.v1.ProjectList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.arangodb.cloud.resourcemanager.v1.Project.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.ProjectList}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.arangodb.cloud.resourcemanager.v1.ProjectList;
  return proto.arangodb.cloud.resourcemanager.v1.ProjectList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.ProjectList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.arangodb.cloud.resourcemanager.v1.ProjectList}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.arangodb.cloud.resourcemanager.v1.Project;
      reader.readMessage(value,proto.arangodb.cloud.resourcemanager.v1.Project.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.arangodb.cloud.resourcemanager.v1.ProjectList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.arangodb.cloud.resourcemanager.v1.ProjectList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.arangodb.cloud.resourcemanager.v1.Project.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Project items = 1;
 * @return {!Array<!proto.arangodb.cloud.resourcemanager.v1.Project>}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.arangodb.cloud.resourcemanager.v1.Project>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.arangodb.cloud.resourcemanager.v1.Project, 1));
};


/** @param {!Array<!proto.arangodb.cloud.resourcemanager.v1.Project>} value */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.setItemsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.arangodb.cloud.resourcemanager.v1.Project=} opt_value
 * @param {number=} opt_index
 * @return {!proto.arangodb.cloud.resourcemanager.v1.Project}
 */
proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.arangodb.cloud.resourcemanager.v1.Project, opt_index);
};


proto.arangodb.cloud.resourcemanager.v1.ProjectList.prototype.clearItemsList = function() {
  this.setItemsList([]);
};


goog.object.extend(exports, proto.arangodb.cloud.resourcemanager.v1);
