title: ArangoDB Oasis API
remote_theme: pmarsceill/just-the-docs
__theme: cayman
highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
